---

- name: add key
  apt_key:
    url: "{{ php_custom_repositories_key_url }}"
    state: present
  when: php_use_custom_repository
  register: php_key_installed

- name: add repo
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: no
  when: php_key_installed|success and php_use_custom_repository
  register: php_repo_installed
  with_items: "{{ php_custom_repositories }}"

- name: update apt cache
  apt:
    update_cache: yes
  when: php_repo_installed|changed

- name: install apt packages
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: no
    update_cache: yes
    cache_valid_time: 86400
  when: php_repo_installed|success
  with_items: "{{ php_packages }}"

- name: list default pools
  shell: "ls -1 {{ php_fpm_root_dir }}/fpm/pool.d"
  register: default_pools
  changed_when: False

- name: delete default pools
  file:
    path: "{{ php_fpm_root_dir }}/fpm/pool.d/{{ item }}"
    state: absent
  with_items: "{{ default_pools.stdout_lines }}"
  when: item != "pools.conf"

- name: config
  template:
    src: "{{ item }}.j2"
    dest: "{{ php_fpm_root_dir }}/fpm/{{ item }}"
  with_items:
    - opcache.blacklist
    - pool.d/pools.conf
    - php-fpm.conf
    - php.ini
  notify:
    - restart php-fpm
  tags: php_config

- name: config CLI
  template:
    src: "{{ item }}.j2"
    dest: "{{ php_fpm_root_dir }}/cli/{{ item }}"
  with_items:
    - php.ini
  tags: php_config

- name: modules config
  template:
    src: "{{ item }}.j2"
    dest: "{{ php_fpm_root_dir }}/mods-available/{{ item }}"
  with_items:
    - custom.ini
  notify:
    - restart php-fpm
  tags: php_config

- include: composer.yml
  when: php_composer_enabled
  tags: php_composer

- include: blackfire.yml
  when: php_blackfire_enabled
  tags: php_blackfire

- include: newrelic.yml
  when: php_newrelic_enabled
  tags: php_newrelic

- include: memcache_mcrouter.yaml
  when: php_memcache_mcrouter_enabled
  tags: php_memcache_mcrouter

- name: enable modules
  shell: "/usr/sbin/phpenmod {{ item }}"
  with_items:
    - newrelic
    - custom
  notify:
    - restart php-fpm
  changed_when: False
  tags: php_config

- name: service start
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "{{ php_fpm_daemon }}"
